import React from "react";

const page = () => {
    return (
        <div className="p-8 pt-36">
            <h1 className="text-2xl font-semibold mb-6">Terms and Conditions</h1>

            <p className="mt-4">Welcome to Golden Ghaf Trading & Consultancy LLP!</p>

            <p className="mt-4">The terms and conditions as set out herein (&#34;Terms&#34;) constitute an agreement between Golden Ghaf Trading & Consultancy Private Limited (&#34;we&#34;, &#34;us&#34; or &#34;our&#34;), which operates the Golden Ghaf Website&#39;s (defined below) and a natural or legal person who accesses and/or uses Golden Ghaf websites in any manner (&#34;you&#34; or &#34;your&#34;) or uses any current or future service or functionality or offer made available on Golden Ghaf websites (&#34;Service(s)&#34;), as updated from time to time.</p>

            <p className="mt-4">By using the Golden Ghaf&#39;s Websites, you expressly agree to be bound by the Terms. If you do not agree with any of the Terms, please do not use the Golden Ghaf&#39;s Websites. If you have any questions about the terms, please contact at Care@ggccomp.in. Please note that your access to the Services, other platforms or utilisation of Products (defined below), offers or promotions in relation to the Products as may be provided by us or our affiliates, may be governed by other terms and conditions, policies or guidelines (&#34;Additional Terms&#34;) along with these Terms. If these Terms are inconsistent with any Additional Terms, the Additional Terms will control to the extent of such inconsistency with respect to the applicable Service or utilisation of the Product. These Terms govern your use of the Golden Ghaf&#39;s website and transaction or dealings thereon. on which you may avail the Services and includes applications controlled and managed by us which interact with one or more such mobile applications/ wallets/ websites/ tablets and digital modes as provided by us; (b) &#34;Products&#34; shall mean apparel, accessories, Home products and other products offered for sale to you on the Golden Ghaf websites; and (c) We and you are hereinafter individually referred to as &#34;Party&#34; and collectively as &#34;Parties&#34;.</p>

            <p className="mt-4">These Terms are divided into 2 (two) parts. Please carefully read all the parts to understand the conditions applicable in case of usage of the Golden Ghaf and for purchase of Products thereof.</p>

            <h2 className="text-xl font-semibold mt-6">PART A &#45; TERMS AND CONDITIONS FOR USAGE OF GOLDEN GHAF</h2>

            <h3 className="text-lg font-semibold mt-4">1. GENERAL</h3>
            <p className="mt-4">1.1 The terms and conditions for usage of the Golden Ghaf as set out herein (&#34;Terms of Use&#34;) specifically govern your access and use of the Golden Ghaf website, which provides a forum for you to inter alia enable you to discover, select and buy Products listed on Golden Ghaf at the indicated price at any time, from the locations serviceable by us.</p>

            <p className="mt-4">1.2 Please note that we may from time to time change the Terms of Use that govern your use of the Golden Ghaf website. Every time you wish to use our Golden Ghaf website, please check these Terms of Use to ensure you understand the terms and conditions that apply at that time. Further, please note that we reserve the right to either change the format and the content of the Golden Ghaf or suspend the operation of the Golden Ghaf for support or maintenance work, in order to update the content or for any other reason, at any time.</p>

            <p className="mt-4">1.3 Any accessing, browsing, or otherwise using the Golden Ghaf Website indicates your agreement to these Terms of Use, the privacy policy of Golden Ghaf (available here: privacy policy) and any other policies or guidelines that may be applicable on the Golden Ghaf Website at the time of your access and usage of the Golden Ghaf Website and which may be updated from time to time (collectively, the &#34;Agreement&#34;).</p>

            <p className="mt-4">1.4 This document is an electronic record in terms of the Information Technology Act, 2000 and rules made thereunder as may be applicable, and the amended provisions pertaining to electronic records in various statutes as amended by the Information Technology Act, 2000. This electronic record is generated by a computer system and does not require any physical or digital signatures.</p>

            <p className="mt-4">1.5 We authorise you to view and access the Golden Ghaf solely for identifying Products, carrying out purchases of Products and processing returns and refunds, in accordance with Return and Refund Policy, therefore, grant you a limited, revocable permission to access and use the Services.</p>

            <p className="mt-4">1.6 By accepting this Agreement, you affirm that you are 18 (Eighteen) years of age or above and are fully competent to enter into this Agreement, and to abide by and comply with this Agreement. If a user is below 18 (Eighteen) years of age, it is assumed that he/she is using/browsing the Golden Ghaf under the supervision of his/her parent or legal guardian and that such user&#39;s parent or legal guardian has read and agrees to the terms of this Agreement, including terms of purchase of Products on behalf of the minor user. In the event we are made aware that a user is under the age of 18 and is using/browsing the Golden Ghaf without the supervision of his/her parent or legal guardian, we reserve the right to deactivate such user&#39;s account without further notice. Further, if you are using the Services on behalf of a company or organisation, you represent that you have authority to act on behalf of that entity, and that such entity accepts this Agreement.</p>

            <h2 className="text-xl font-semibold mt-6">2. REGISTRATION OF YOUR GOLDEN GHAF ACCOUNT</h2>
            <p className="mt-4">2.1 In order to purchase Products on the Golden Ghaf and/or avail the Services, you will have to register on the Golden Ghaf. Registration is a one-time process based on successful mobile OTP (One Time Password) verification and you will be eligible to further access and avail the Services only after filling in the necessary forms and details as may be required by us at the time of your registration. For placing an order, you should login to your account by completing the successful mobile OTP verification.</p>
            <p className="mt-4">2.2</p>
            <p className="mt-4">2.3 You are solely authorized to operate the account created by you. Consequently, it is your responsibility to maintain the confidentiality of the log in credentials of your account on the Golden Ghaf&#39;s websites and for restricting access to your computer/mobile/other similar devices to prevent unauthorized access to your account. You shall remain solely liable for all the actions undertaken through your account.</p>
            <p className="mt-4">2.4 You will: (a) immediately inform us of any unauthorized use of the account or any other security breach; and (b) ensure that you log out of your account at the end of each session. We, our employees, agents, directors and officers will not be liable for any loss or direct or indirect damage arising from your failure to comply with these Terms of Use. You may be held liable for any losses incurred to us or any other user due to unauthorized use of their account by you. We reserve the right to refuse access to the Golden Ghaf&#39;s websites, terminate accounts, remove or edit content at any time without notice to you.</p>

            <h3 className="text-lg font-semibold mt-4">3. COMMUNICATION AND UNSUBSCRIPTION</h3>
            <p className="mt-4">3.1 By accepting the Terms of Use, you also accept to receive news, updates, offers/ campaign related SMS, to the mobile phone number provided by you. By accessing and using the Golden Ghaf and/ or verifying your contact number with us, you explicitly consent to receive such communications (through call, SMS, email or other digital and electronic means) from us and/or our authorized representatives regarding any new services or offerings, even if your contact number is registered under the DND/NCPR list under the Telecom Commercial Communications Customer Preference Regulations, 2018.</p>
            <p className="mt-4">3.2 You can unsubscribe/ opt-out from receiving marketing/ promotional communications, newsletters and other notifications from us at any time by following the instructions set out in such communications.</p>

            <h3 className="text-lg font-semibold mt-4">4. DISCLAIMER OF WARRANTIES, INACCURACIES OR ERRORS</h3>
            <p className="mt-4">4.1 We will try to ensure that all information and recommendations, whether in relation to the Products, Services, offerings or otherwise (hereinafter &#34;Information&#34;) provided as part of this Golden Ghaf is correct at the time of inclusion on the Golden Ghaf. We do not guarantee the accuracy of the Information. We make no representations or warranties as to the completeness or accuracy of Information.</p>
            <p className="mt-4">4.2 You agree that Information is being supplied to you on the condition that you will make your own determination as to the suitability of such information for your purpose prior to use or in connection with the making of any decision. No Information on the Golden Ghaf website shall constitute an invitation to invest in us or any affiliates. Any use of this Golden Ghaf or the Information is at your own risk. Neither we, our affiliates, nor their officers, employees or agents shall be liable for any loss, damage or expense arising out of any access to, use of, or reliance upon, this website, the Information, or any third-party website linked to Golden Ghaf. We are not responsible for the content of any third-party sites and do not make any representations regarding the content or accuracy of material on such sites. If you decide to access links of any third-party platforms, you are doing so entirely at your own risk and expense.</p>
            <p className="mt-4">4.3 As means to assist the users in identifying the Products of their choice, we provide visual representations on the Golden Ghaf website including graphics, illustrations, photographs, images, videos, charts, screenshots, infographics and other visual aids. While reasonable efforts are made to provide accurate visual representation, we disclaim any guarantee or warranty of exactness of such visual representation or description of the Product, with the actual Product ultimately delivered to users. The appearance of the Product when delivered may vary for various reasons.</p>
            <p className="mt-4">4.4 Nothing contained herein is to be construed as a recommendation to use any Product, process, equipment or formulation, in conflict with any patent, or otherwise and we make no representation or warranty, express or implied that, the use thereof will not infringe any patent, or otherwise.</p>
            <p className="mt-4">4.5 We do not covenant or provide any representations and warranties:</p>
            <ul>
                <li>4.5.1 in respect of quality, suitability, accuracy, reliability, performance, safety, merchantability, fitness for a particular purpose/consumption or the content (including Product or pricing information and/or specifications) on Golden Ghaf</li>
                <li>4.5.2 that the Services will be made available at all times; and</li>
                <li>4.5.3 that the operation of Golden Ghaf including the functions contained in any content, information and materials on Golden Ghaf or any third-party sites or services linked to Golden Ghaf will be uninterrupted, or that the defects will be rectified, or that websites or the servers that make such content, information and materials available are free of viruses or other harmful components.</li>
            </ul>
            <p className="mt-4">4.6 THIS GOLDEN GHAF AND THE SERVICES ARE PROVIDED TO YOU ON AN &#34;AS IS&#34; AND &#34;WHERE-IS&#34; BASIS, WITHOUT ANY REPRESENTATIONS OR WARRANTIES. WE, FOR OURSELF AND ANY THIRD-PARTY PROVIDING MATERIALS, SERVICES, OR CONTENT TO THIS WEBSITE, MAKE NO REPRESENTATIONS OR WARRANTIES, EITHER EXPRESS, IMPLIED, STATUTORY OR OTHERWISE OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, OR NONINFRINGEMENT OF THIRD-PARTY RIGHTS, WITH RESPECT TO THE GOLDEN GHAF THE INFORMATION OR ANY PRODUCTS OR SERVICES TO WHICH THE INFORMATION REFERS. WE WILL NOT BE LIABLE TO YOU OR ANY THIRD PARTY FOR ANY DAMAGES OF ANY KIND, INCLUDING BUT NOT LIMITED TO, DIRECT, INDIRECT, INCIDENTAL, CONSEQUENTIAL OR PUNITIVE DAMAGES, ARISING FROM OR CONNECTED WITH THE SITE, INCLUDING BUT NOT LIMITED TO, YOUR USE OF THIS SITE OR YOUR INABILITY TO USE THE SITE, EVEN IF WE HAVE PREVIOUSLY BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES.</p>
            <p className="mt-4">4.7 Disclaimer -To the extent permitted by applicable law, We, our officers, agents, employees and directors, disclaim any liability against any loss, damage, expenses, liabilities, claim, injury caused due to the failure of performance, omission, defect of products, or deletion, interruption, error, delay, virus, communication, unauthorised access, theft, destruction, alteration or use of records on the Golden Ghaf.</p>

            <h3 className="text-lg font-semibold mt-4">1. GENERAL</h3>
            <p className="mt-4">1.1 The terms and conditions for usage of the Golden Ghaf as set out herein (&#34;Terms of Use&#34;) specifically govern your access and use of the Golden Ghaf website, which provides a forum for you to inter alia enable you to discover, select and buy Products listed on Golden Ghaf at the indicated price at any time, from the locations serviceable by us.</p>

            <p className="mt-4">1.2 Please note that we may from time to time change the Terms of Use that govern your use of the Golden Ghaf website. Every time you wish to use our Golden Ghaf website, please check these Terms of Use to ensure you understand the terms and conditions that apply at that time. Further, please note that we reserve the right to either change the format and the content of the Golden Ghaf or suspend the operation of the Golden Ghaf for support or maintenance work, in order to update the content or for any other reason, at any time.</p>

            <h3 className="text-lg font-semibold mt-4">5. AVAILABILITY AND ACCESSIBILITY OF GOLDEN GHAF</h3>
            <p className="mt-4">5.1 We control and operate this Golden Ghaf from India and make no representation that the materials and the content available on the Golden Ghaf are appropriate to be used or will be available for use in other locations outside India. If you use this Golden Ghaf from outside India, you are entirely responsible for compliance with all applicable local laws. These Terms of Use do not constitute, nor may these Terms of Use be used for or in connection with any promotional activities or solicitation by anyone in any jurisdiction in which such promotional activities or solicitation are not authorized or to any person to whom it is unlawful to promote or solicit.</p>

            <p className="mt-4">5.2 We have several websites offering Products, Services, content and various other functionalities to specific regions worldwide. The Services offered in one region may differ from those in other regions due to availability, local or regional laws, shipment and other considerations. We do not make any warranty or representation that a user in one region may obtain the Services from our site in another region and we may cancel a user&#39;s order or redirect a user to the site for that user&#39;s region if a user attempts to order Services offered on a site in another region.</p>

            <p className="mt-4">5.3 Information that we publish on the world wide web may contain references or cross references to our Products, programs and Services that are not announced or available in your country. Such references do not imply that we intend to announce such Products, programs or Services in your country. Consult our local business contact for information regarding the Products, programs and Services that may be available to you.</p>

            <p className="mt-4">5.4 We constantly monitor the user&#39;s account in order to avoid fraudulent accounts and transactions. Users with more than one account or availing referral vouchers fraudulently shall be liable for legal actions under law and we reserve the right to recover the cost of goods, collection charges and lawyer fees from persons using the Golden Ghaf fraudulently. We reserve the right to initiate legal proceedings against such persons for fraudulent use of the Golden Ghaf and any other unlawful acts or omissions in breach of these terms and conditions. In the event of detection of any fraudulent or declined transaction, prior to initiation of legal actions, we reserve the right to immediately delete such account and dishonour all past and pending orders without any liability. For the purpose of this clause, we shall owe no liability for any refunds.</p>

            <h3 className="text-lg font-semibold mt-4">6. THIRD PARTY INTERACTION AND LINKS TO THIRD PARTY SITES</h3>
            <p className="mt-4">6.1 In your use of Golden Ghaf you may enter into correspondence with, purchase goods and/or services from, or participate in promotions of advertisers or members or sponsors of Golden Ghaf or access any other third-party website linked to the Golden Ghaf. Unless otherwise stated, any such correspondence, advertisement, purchase or promotion, including the delivery of and the payment for goods and/or services, and any other term, condition, warranty or representation associated with such correspondence, purchase or promotion, is solely between you and the applicable third party. You agree that we have no liability, obligation or responsibility for any such correspondence, purchase or promotion, access or usage of any third-party website and the contract under such instances remains between you and any such third party.</p>

            <h3 className="text-lg font-semibold mt-4">7. COPYRIGHTS IN GOLDEN GHAF CONTENT</h3>
            <p className="mt-4">7.1 The Golden Ghaf contains material, including text, graphics and sound, which is protected by copyright and/or other intellectual property rights (&#34;Golden Ghaf Content&#34;). All copyright and other intellectual property rights in the Golden Ghaf Content are either owned by us or have been licensed to us by the owner(s) of those rights so that it can use the Golden Ghaf Content as part of Golden Ghaf. We retain copyright on all Information, including text, graphics and sound and all trademarks displayed on the Golden Ghaf are either owned by or licensed to us.</p>

            <p className="mt-4">7.2 You may use and display the Golden Ghaf Content on your personal computer only for your personal use subject to the grant of a limited, revocable, personal, non-exclusive and non-transferable license to you by us when you register on the Golden Ghaf only for identifying Products, carrying out purchases of Products and processing returns and refunds in accordance with our Return and Refund Policy and for using and printing copies of the information on the Golden Ghaf for your personal use and store the files on your computer for personal use only and not for business purposes.</p>

            <p className="mt-4">7.3 You may not: (a) copy (whether by printing off onto paper, storing on disk, downloading or in any other way), distribute (including distributing copies), download, display, perform, reproduce, distribute, modify, edit, alter, enhance, broadcast or tamper within any way or otherwise use any Golden Ghaf Content contained in the Golden Ghaf. These restrictions apply in relation to all or part of the Golden Ghaf Content available on the Golden Ghaf; (b) copy and distribute the Information on any other server, or modify or re-use text or graphics on this system or another system; (c) reproduce any part of the Golden Ghaf or sell or distribute the same for commercial gain nor shall it be modified or incorporated in any other work, publication or web site, whether in hard copy or electronic format, including postings to any other web site; (d) remove any copyright, trademark or other intellectual property notices contained in the original material from any material copied or printed off from Golden Ghaf; or (e) link any other material to the Golden Ghaf without our express written consent.</p>

            <p className="mt-4">7.4 The license granted to you does not include a license for: (a) resale of Products or commercial use of the Golden Ghaf or Golden Ghaf Content, (b) any collection and use of product listings, description, or prices, (c) any use of Golden Ghaf the Services and/or of Golden Ghaf Content other than as contemplated in these Terms of Use, (d) any downloading or copying of login credentials of user, (e) any use of data mining, robots, or similar data gathering and extraction tools to extract (whether once or many times) any parts of Golden Ghaf, and (f) creating and/ or publishing your own database that features parts of the Golden Ghaf.</p>

            <p className="mt-4">7.5 If you believe that your intellectual property rights have been used in a way that raises concerns of infringement, please write to us at Care@ggccomp.in and let us know of your concerns.</p>

            <h3 className="text-lg font-semibold mt-4">8. TRADEMARKS</h3>
            <p className="mt-4">All the trade names associated with us and all Products and logos denoted with TM are trademarks or registered trademarks of us or our affiliates. Our trademarks may not be used in connection with any product or service that is not our product or service.</p>

            <h3 className="text-lg font-semibold mt-4">9. LICENSE AND USE OF GOLDEN GHAF&#39;S YOUR CONTENT</h3>
            <p className="mt-4">9.1 You grant to us a royalty-free, perpetual, irrevocable, non-exclusive right and license to adopt, publish, reproduce, disseminate, transmit, distribute, copy, use, create derivative works from, display worldwide, or act on any material posted by you on the Golden Ghaf without additional approval or consideration in any form, media, or technology now known or later developed, for the full term of any rights that may exist in such content, and you waive any claim over all feedback, comments, ideas or suggestions or any other content provided through or on the Golden Ghaf. You agree to perform all further acts necessary to perfect any of the above rights granted by you to us, including the execution of deeds and documents, at its request.</p>

            <p className="mt-4">9.2 You agree that we do not routinely monitor your postings on Golden Ghaf but reserve the right to do so. However, if we become aware of inappropriate use of the Golden Ghaf or any of its Services, we will respond in any way that we, in our sole discretion, deem appropriate. We are not responsible for any user content posted or transmitted through Golden Ghaf, or for any loss or damage arising from your failure to comply with these Terms of Use. You are solely responsible for any user content you post, and you will indemnify us for any damage resulting from any user content that you post or transmit.</p>

            <p className="mt-4">9.3 Submissions and unauthorised use of any materials contained on the Golden Ghaf may violate copyright laws, trademark laws, the laws of privacy and publicity, certain communications statutes and regulations and other applicable laws and regulations. You alone are responsible for your actions or the actions of any person using your username and/or password. As such, you shall indemnify and hold us and our officers, directors, employees, affiliates, agents, licensors, and business partners harmless from and against any and all loss, costs, damages, liabilities, and expenses (including attorneys&#39; fees) incurred in relation to, arising from, or for the purpose of avoiding, any claim or demand from a third party that your use of the Golden Ghaf or the use of the Golden Ghaf by any person using your user name and/or password (including without limitation your participation in the posting areas or your Submissions) violates any applicable law or regulation, or the rights of any third party.</p>

            <p className="mt-4">9.4 We reserve the right to terminate access to this Golden Ghaf at any time and without notice. Further this limited license terminates automatically, without notice to you, if you breach any of these Terms of Use. Upon termination, you must immediately destroy any downloaded and printed materials. Any provision of the Terms of Use which imposes an obligation or creates a right that by its nature will be valid after termination or expiration of the Terms of Use shall survive the termination or expiration of the Terms of Use.</p>

            <h3 className="text-lg font-semibold mt-4">10. USER WARRANTIES AND RESTRICTIONS AT GOLDEN GHAF</h3>
            <p className="mt-4">10.1 You represent and warrant that: (a) your use of Golden Ghaf and/or Services will not violate any applicable law or regulation; (b) all information that is submitted to us in connection with Golden Ghaf and/or Services is true, accurate and lawful; (c) use of the content and material you supply does not breach any applicable Agreement and will not cause injury to any person or entity (including that the content or material is not defamatory). If at any time, the information provided by you is found to be false or inaccurate, we will have the right to reject registration, cancel all orders, and restrict you from using the Services and other affiliated services in the future without any prior intimation whatsoever. You agree to indemnify us and our affiliates for all claims brought by a third party against it or its affiliates arising out of or in connection with a breach of any of these warranties.</p>


            <p className="mt-4">10.2 You will use Golden Ghaf for lawful purposes only and will not undertake any activity that is harmful to Golden Ghaf or its content or otherwise not envisaged through the Golden Ghaf. You have a limited license to access and use Golden Ghaf, solely for the purpose of availing the Services, subject to these Terms of Use.</p>

<p className="mt-4">10.3 You will not do any of the following:</p>

<p className="mt-4">10.3.1 Delete or modify any content on Golden Ghaf, such as any information regarding the Services, their performance, sales or pricing;</p>

<p className="mt-4">10.3.2 Use any engine, software, tool, agent or other mechanism (such as spiders, robots, avatars, worms, time bombs etc.) to navigate or search Golden Ghaf;</p>

<p className="mt-4">10.3.3 Make false or malicious statements against the Services, Golden Ghaf or us;</p>

<p className="mt-4">10.3.4 Post, copy, submit, upload, distribute, or otherwise transmit or make available any software or other computer files that contain a virus or other harmful component, or otherwise disrupt or damage Golden Ghaf and/or Services or any connected network, or otherwise interfere with any person or entity&#39;s use or enjoyment of Golden Ghaf and/or the Services;</p>

<p className="mt-4">10.3.5 Introduce any trojans, viruses, any other malicious software, any bots or scrape Golden Ghaf for any information;</p>

<p className="mt-4">10.3.6 Probe, scan, or test the vulnerability of any system, security or authentication measures implemented by us or otherwise tamper or attempt to tamper with our technological design and architecture;</p>

<p className="mt-4">10.3.7 Hack into or introduce malicious software of any kind onto Golden Ghaf;</p>

<p className="mt-4">10.3.8 Gain unauthorized access to, or interfere with, or damage, or disrupt the server on which the details connected to the Services are stored, or any other server, computer, or database connected to the Services; or</p>

<p className="mt-4">10.3.9 Engage in any form of antisocial, disruptive, or destructive acts, including &#34;flaming,&#34; &#34;spamming,&#34; &#34;flooding,&#34; &#34;trolling,&#34; &#34;phishing&#34; and &#34;griefing&#34; as those terms are commonly understood and used on the internet.</p>

<p className="mt-4">10.4 You are prohibited from hosting, displaying, uploading, modifying, publishing, transmitting, updating or sharing on or through Golden Ghaf, any information that:</p>

<p className="mt-4">10.4.1 belongs to another person and to which you do not have any right;</p>

<p className="mt-4">10.4.2 is harmful, harassing, blasphemous, defamatory, obscene, pornographic, paedophilic, invasive of another&#39;s privacy, hateful, relating to or encouraging money laundering or gambling, or otherwise harmful in any manner whatsoever;</p>

<p className="mt-4">10.4.3 harms minors in any way;</p>

<p className="mt-4">10.4.4 infringes any patent, trademark, copyright or other proprietary rights;</p>

<p className="mt-4">10.4.5 violates any law for the time being in force;</p>

<p className="mt-4">10.4.6 deceives or misleads the addressee about the origin of such messages or communicates any information which is grossly offensive or menacing in nature;</p>

<p className="mt-4">10.4.7 impersonates or defames another person; or</p>

<p className="mt-4">10.4.8 Contains software viruses or any other computer code, files or programs designed to interrupt, destroy or limit the functionality of any computer resource.</p>

<h3 className="text-lg font-semibold mt-4">11. INDEMNIFICATION AND LIMITATION OF LIABILITY</h3>
<p className="mt-4">You agree to indemnify, defend and hold harmless us, our affiliates, officers, directors, employees, consultants, licensors, agents, and representatives from and against any and all third- party claims, losses, liabilities, damages, and/or costs (including reasonable attorney fees and costs) arising from your access to or use of Golden Ghaf or the Services, violation of these Terms of Use, or infringement of any of our or any third-party intellectual property or other rights. We will notify you promptly of any such claim, loss, liability, or demand, and in addition to the foregoing, you agree to provide us with reasonable assistance, at your expense, in defending any such claim, loss, liability, damage, or cost.</p>

<h3 className="text-lg font-semibold mt-4">12. APPLICABLE LAW AND JURISDICTION</h3>
<p className="mt-4">These Terms of Use are governed by and to be interpreted in accordance with laws of India, without regard to the choice or conflicts of law provisions of any jurisdiction. You agree, in the event of any dispute arising in relation to these Terms of Use or any dispute arising in relation to the Golden Ghaf whether in contract or tort or otherwise, to submit to the jurisdiction of the courts located at Mumbai, India for the resolution of all such disputes.</p>

<h3 className="text-lg font-semibold mt-4">13. GRIEVANCE OFFICER</h3>
<p className="mt-4">In accordance with the applicable law, any grievances which you may have with respect to the information shared by you with us hereunder and its treatment or any grievance related to Services being availed hereunder, may be directed by you to such grievance officer at the below mentioned coordinate:</p>

<h3 className="text-lg font-semibold mt-4">14. FORCE MAJEURE</h3>
<p className="mt-4">We will not be held responsible for any delay or failure to comply with its obligations if the delay or failure arises from any cause which is beyond our reasonable control.</p>

<h3 className="text-lg font-semibold mt-4">15. WAIVER</h3>
<p className="mt-4">No provision in these Terms of Use will be deemed waived and no breach excused, unless such waiver or consent is in writing and signed by us. Any consent by us to, or waiver of your breach, whether expressed or implied, will not constitute consent to, waiver of, or excuse for any other different or subsequent breach.</p>

<h3 className="text-lg font-semibold mt-4">16. SEVERABILITY</h3>
<p className="mt-4">If any provision of these Terms of Use is held by a court of competent jurisdiction to be unenforceable under applicable law, then such provision will be excluded from these Terms of Use and the remainder of these Terms of Use will be interpreted as if such provision were so excluded and will be enforceable in accordance with its terms; provided however that, in such event, these Terms of Use will be interpreted so as to give effect, to the greatest extent consistent with and permitted by applicable law, to the meaning and intention of the excluded provision as determined by such court of competent jurisdiction.</p>

<h3 className="text-lg font-semibold mt-4">17. AMENDMENT</h3>
<p className="mt-4">These Terms of Use are subject to amendments and modifications and may be updated from time to time, without any advance notice. You are requested to regularly review the Terms of Use as available on Golden Ghaf. Your relationship with the Golden Ghaf will be governed by the most current version of these Terms of Use, as published on Golden Ghaf.</p>


<h3 className="text-lg font-semibold mt-4">PART B &#45; TERMS AND CONDITIONS OF SALE ON GOLDEN GHAF</h3>
<p className="mt-4">The terms and conditions of sale as set out herein (&#34;Terms of Sale&#34;) constitute an agreement between us and you and govern the terms and conditions on which you purchase your Products from us on or through the Golden Ghaf. By placing an order for any Product with us or making a purchase of Product, you expressly agree to be bound by these Terms of Sale.</p>

<p className="mt-4">These Terms of Sale are in addition to the Agreement. These Terms of Sale constitute an electronic record within the meaning of the applicable law. This electronic record is generated by a computer system and does not require any physical or digital signatures.</p>

<h3 className="text-lg font-semibold mt-4">1. GOLDEN GHAF&#39;S CONTRACT OF SALE</h3>
<p className="mt-4">1.1. Listing and display of a Product by us on Golden Ghaf is our invitation to you to make an offer for purchase of such Product. Likewise, the placement of an order on Golden Ghaf&#39;s websites by you is your offer to buy the Product(s) from us.</p>

<p className="mt-4">1.2. Once you have placed an order with us for purchase of a Product, you will receive an e&#45;mail and/or mobile confirming receipt of your order and containing the details of your order (the &#34;Order Confirmation&#34;). The Order Confirmation is merely an acknowledgement that we have received your order and does not signify our acceptance of your offer.</p>

<p className="mt-4">1.3. We only accept your offer and conclude the contract of sale for a Product ordered by you, when the Product is shipped or dispatched to you and an e&#45;mail and/or registered mobile number confirmation is sent to you that the Product has been shipped or dispatched to you (the &#34;Shipment Confirmation&#34;). We reserve the right, at our sole discretion, to refuse or cancel any order for any reason whatsoever before sending Shipment Confirmation to you.</p>

<p className="mt-4">1.4. If your order is dispatched in more than one package, you may receive separate Shipment Confirmations for each package, and each Shipment Confirmation and corresponding dispatch will conclude a separate contract of sale between you and us for the Product(s) specified in that Shipment Confirmation.</p>

<p className="mt-4">1.5. Any communication from us shall be sent only to your registered mobile number and/or email address or such other contact number or email address that you may designate, for any particular transaction. You shall be solely responsible to update your registered mobile number and/or email address on the Golden Ghaf&#39;s websites in the event there is a change. Further, we may also send you notifications and reminders with respect to scheduled deliveries of the purchased Products. While we shall make every endeavour to share prompt reminders and notifications relating to the delivery of purchased Product(s) with you, we shall not be held liable for any failure to send such notifications or reminders to you.</p>

<p className="mt-4">1.6. Your contract is with us and you confirm that the Product(s) ordered by you are purchased for your internal / personal purpose and not for re&#45;sale or business purpose. Please note that we sell Products only in quantities which correspond to the usual requirements of an average household. This applies both to the number of Products ordered within a single order and the placing of several orders for the same Product where the individual orders comprise a quantity typical for a normal household.</p>

<p className="mt-4">1.7. All orders placed on Golden Ghaf&#39;s websites are subject to the availability of such Product, our acceptance of your offer as per the above and your continued adherence to these Terms of Sale.</p>

<p className="mt-4">1.8. You hereby authorise us to declare and provide declarations to any governmental authority on request on your behalf, including that the Products ordered by you are for personal, non&#45;commercial use.</p>

<h3 className="text-lg font-semibold mt-4">2. RETURN AND REFUND</h3>
<p className="mt-4">Please review the Returns Policy and Refund Policy of Golden Ghaf, which applies to Products sold by us.</p>

<h3 className="text-lg font-semibold mt-4">3. PRODUCT AVAILABILITY</h3>
<p className="mt-4">We list availability information for the Products on the relevant webpage of Golden Ghaf&#39;s websites. Beyond what we say on that webpage or otherwise on Golden Ghaf&#39;s websites, we cannot be more specific about availability. Please note that dispatch estimates are not guaranteed and should not be relied upon as such. As we process your order, you will be informed by e&#45;mail and/or mobile SMS if any Products you order turn out to be unavailable or out of stock.</p>

<h3 className="text-lg font-semibold mt-4">4. PRODUCT PRICING</h3>
<p className="mt-4">4.1. All prices are listed in Indian Rupees. Price, as displayed, is inclusive of all applicable taxes.</p>

<p className="mt-4">4.2. Products in your shopping cart of Golden Ghaf&#39;s websites will reflect the most recent price as displayed on the Product&#39;s information webpage on Golden Ghaf&#39;s websites. Please note that this price may differ from the price shown for the Product when you first placed it in your shopping cart. Placing a Product in your shopping cart does not reserve the price shown at that time. It is also possible that a Product&#39;s price may decrease between the time you place it in your shopping cart and the time you place the order. The prices mentioned at the time of ordering will be the prices charged on the date of the delivery.</p>

<h3 className="text-lg font-semibold mt-4">5. LICENSES</h3>
<p className="mt-4">You acknowledge that there may be licenses/permissions required under the applicable laws to use, purchase or otherwise possess certain Product(s). You will be solely responsible for obtaining such licenses/permissions and complying with the terms of such licenses/permissions.</p>

<h3 className="text-lg font-semibold mt-4">6. TAXES</h3>
<p className="mt-4">You shall be responsible for payment of all fees/costs/charges associated with the purchase of Products from us and you agree to bear any and all applicable taxes.</p>

<h3 className="text-lg font-semibold mt-4">7. ELIGIBILITY</h3>
<p className="mt-4">Only persons who can enter into legally binding contracts as per Indian Contract Act, 1872, i.e., persons who are 18 (Eighteen) years of age or older, are of sound mind, and are not disqualified from entering into contracts by any law, can use Golden Ghaf&#39;s websites and place an order with us. If you are a minor i.e., under the age of 18 (Eighteen) years, you may purchase the Product on Golden Ghaf&#39;s websites only with the involvement of a parent or guardian.</p>

<h3 className="text-lg font-semibold mt-4">8. LIMITATION OF LIABILITY</h3>
<p className="mt-4">In no event, our aggregate liability, if any, that is proven and ordered by a court of competent jurisdiction pursuant to a claim by you or person acting on your behalf, shall extend beyond the money charged from you for purchases made pursuant to an order under which such liability has arisen and been established. We will not be responsible for any business loss (including loss of profits, revenue, contracts, anticipated savings, data, goodwill or wasted expenditure) or any other indirect or consequential loss that is not reasonably foreseeable to both you and us when a contract for the sale of Product by us to you was formed.</p>

<h3 className="text-lg font-semibold mt-4">9. AMENDMENTS</h3>
<p className="mt-4">We reserve the right to make changes to our policies, and these Terms of Sale at any time. You will be subject to the policies and Terms of Sale in force at the time you order Product from us, unless any change to those policies or these Terms of Sale is required to be made by law or government authority (in which case it will apply to orders previously placed by you). If any of these conditions is deemed invalid, void, or for any reason unenforceable, that condition will be deemed severable and will not affect the validity and enforceability of any remaining condition.</p>

<h3 className="text-lg font-semibold mt-4">10. FORCE MAJEURE</h3>
<p className="mt-4">We will not be held responsible for any delay or failure to comply with its obligations if the delay or failure arises from any cause which is beyond our reasonable control.</p>

<h3 className="text-lg font-semibold mt-4">11. WAIVER</h3>
<p className="mt-4">No provision in these Terms of Sale will be deemed waived and no breach excused, unless such waiver or consent is in writing and signed by us. Our consent to, or waiver of your breach, whether expressed or implied, will not constitute consent to, waiver of, or excuse for any other different or subsequent breach.</p>

<h3 className="text-lg font-semibold mt-4">12. GOVERNING LAW AND DISPUTE RESOLUTION</h3>
<p className="mt-4">These Terms of Sale, all transactions consummated between you and us, and our relationship with you is governed by the laws of India, without reference to any conflict of laws principles and with an exclusive jurisdiction to the courts of Mumbai.</p>

<h3 className="text-lg font-semibold mt-4">13. MISCELLANEOUS</h3>
<p className="mt-4">13.1. In addition to these Terms of Sale, you will also ensure that you are in compliance with the terms and conditions of the third parties, such as bank offers terms and conditions, brand promotional offers, whose links, if any, are contained/embedded in the Terms of Use.</p>

<p className="mt-4">13.2. These Terms of Sale supersede all previous oral and written terms and conditions (if any) communicated to you by us, for the purchase of Product.</p>


<h2 className="text-xl font-semibold mt-6">CONTACT US</h2>
            <p className="mt-4">If you have any questions or concerns about these terms and conditions or our practices, please contact us at:</p>
            <p className="mt-4">Customer Care Email: Care@ggccomp.in</p>
            <p className="mt-4">Contact No & WhatsApp No: +91 9930005234</p>
        </div>
    );
};

export default page;
